ExoticsOwnersRegistry/Models/DataTables/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

// This is added to insure warning on non CLS complaint Keys
[assembly: CLSCompliant(true)]

namespace ExoticsOwnersRegistry.Models
{
    public enum eApprovalStatus
    {
        Submitted = 0,
        Pending = 1,
        Accepted = 2,
        Rejected = 3
    };

    public class Car
    {
        // Key type MUST BE CLS compliant!
        [Key]
        public Int64 carID { get; set; }

        // One to one car to make relationship
        [ForeignKey("carMaker")]
        public Int64? makeID { get; set; }
        [Display(Name = "Make")]
        public virtual CarMaker carMaker { get; set; }

        // One to one car to model relationship
        [ForeignKey("carModel")]
        public Int64? modelID { get; set; }
        [Display(Name = "Model")]
        public virtual CarModel carModel { get; set; }

        // One to one car to submodel relationship
        [ForeignKey("carSubModel")]
        public Int64? subModelID { get; set; }
        [Display(Name = "Sub-Model")]
        public virtual CarSubModel carSubModel { get; set; }

        [Required]
        public string VIN { get; set; }

        [Display(Name="Showcase Picture")]
        [DataType(DataType.ImageUrl)]
        public byte[] showCaseCarPicture { get; set; }

        // One to one current owner to car relationship
        [ForeignKey("owner")]
        public Int64 ownerID { get; set; }
        [Display(Name = "Current Owner")]
        public virtual Owner owner { get; set; }

        // Details about the car : 1 to 1 relationship
        // Note: Virtual allow lazy loading to work - critical
        [Display(Name="Car Details")]
        public virtual CarDetails carDetails { get; set; }

        //// One to many car to history period
        //// Note: Virtual allow lazy loading to work - critical
        //public virtual List<HistoryPeriod> historyList { get; set; }

        //// List of one car to many public auctions
        //// Note: Virtual allow lazy loading to work - critical
        //public virtual List<Auction> auctionList { get; set; }

        //// List of one car to many tags during the car's life
        //TODO - NO: MANY CAR TO MANY TAGS 
        //public virtual List<LicenceTag> licenseTagList { get; set; }
        
        //// List of one car to many information submitters
        //// Note: Virtual allow lazy loading to work - critical
        //public virtual List<Submitter> submitterList { get; set; }

        //// List of one car to many awards
        //// Note: Virtual allow lazy loading to work - critical
        //public virtual List<Award> awardList { get; set; }

        //// List of one car to many sales
        //// Note: Virtual allow lazy loading to work - critical
        //public virtual List<Sale> saleList { get; set; }

        ////////////// Internal dbase data ///////////////

        //[DataType(DataType.DateTime)]
        //[DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        //public byte[] createdDate { get; set; }

        //[DataType(DataType.DateTime)]
        //[DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        //public byte[] LastModifiedDate { get; set; }

        // Car privacy except owner
        [Display(Name = "Hidden Record")]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool bHideCar { get; set; }

        // Submittion approval
        //TODO create an enum dropdown
        [Display(Name = "Approval Status")]
        public int approvalStatus { get; set; }

        // [Timestamp] is necesssary to concurency detection and exception 
        // [Browsable] is neccessary to hide the property from view binding
        [Timestamp]
        [Browsable(false)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public byte[] TimeStamp { get; set; }
    }
}

ExoticsOwnersRegistry/Controllers/CarDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExoticsOwnersRegistry.Models;

namespace ExoticsOwnersRegistry.Controllers
{
    public class CarDetailsController : Controller
    {
        private ExoticsOwnersRegistryContext db = new ExoticsOwnersRegistryContext();

        // GET: CarDetails
        public async Task<ActionResult> Index()
        {
            var carDetails = db.carDetails.Include(c => c.car);
            return View(await carDetails.ToListAsync());
        }

        // GET: CarDetails/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarDetails carDetails = await db.carDetails.FindAsync(id);
            if (carDetails == null)
            {
                return HttpNotFound();
            }
            return View(carDetails);
        }

        // GET: CarDetails/Create
        public ActionResult Create()
        {
            ViewBag.carID = new SelectList(db.cars, "carID", "VIN");
            return View();
        }

        // POST: CarDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "carID,originalFuelSystem,currentFuelSystem,originalExteriorColor,originalInteriorColor,currentExteriorColor,currentInteriorColor,modelYear,productionDate,deliveryCountry,deliveryDealership,currentCountryLocation,currentRegionalLocation")] CarDetails carDetails)
        {
            if (ModelState.IsValid)
            {
                db.carDetails.Add(carDetails);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.carID = new SelectList(db.cars, "carID", "VIN", carDetails.carID);
            return View(carDetails);
        }

        // GET: CarDetails/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarDetails carDetails = await db.carDetails.FindAsync(id);
            if (carDetails == null)
            {
                return HttpNotFound();
            }
            ViewBag.carID = new SelectList(db.cars, "carID", "VIN", carDetails.carID);
            return View(carDetails);
        }

        // POST: CarDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "carID,originalFuelSystem,currentFuelSystem,originalExteriorColor,originalInteriorColor,currentExteriorColor,currentInteriorColor,modelYear,productionDate,deliveryCountry,deliveryDealership,currentCountryLocation,currentRegionalLocation")] CarDetails carDetails)
        {
            if (ModelState.IsValid)
            {
                db.Entry(carDetails).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.carID = new SelectList(db.cars, "carID", "VIN", carDetails.carID);
            return View(carDetails);
        }

        // GET: CarDetails/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarDetails carDetails = await db.carDetails.FindAsync(id);
            if (carDetails == null)
            {
                return HttpNotFound();
            }
            return View(carDetails);
        }

        // POST: CarDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            CarDetails carDetails = await db.carDetails.FindAsync(id);
            db.carDetails.Remove(carDetails);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExoticsOwnersRegistry/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;

using ExoticsOwnersRegistry.Models;

namespace ExoticsOwnersRegistry.Controllers
{
    public class CarsController : Controller
    {
        private ExoticsOwnersRegistryContext db = new ExoticsOwnersRegistryContext();

        // GET: Cars
        public async Task<ActionResult> Index()
        {
            var cars = db.cars.Include(c => c.carDetails)
                              .Include(c => c.carMaker)
                              .Include(c => c.carModel)
                              .Include(c => c.carSubModel);

            return View(await cars.ToListAsync());
        }

        // Display cars by Vin
        public ActionResult DisplayCarsByVin()
        {
            //TODO code here
            return View();
        }

        // Display car details 
        public async Task<ActionResult> Show(long? id)
        {
            CarDetails carDetails = await db.carDetails.FindAsync(id);

            return View(carDetails);
        }


        // GET: Cars/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = await db.cars.FindAsync(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // GET: Cars/Create
        // Display the form
        // The Authorize attribute will send the user to the Account controller for login
        //[Authorize]
        public ActionResult Create()
        {
            ViewBag.carID = new SelectList(db.carDetails, "carID");//, "originalExteriorColor");
            ViewBag.makeID = new SelectList(db.carMakers, "makeID", "makeName");
            ViewBag.modelID = new SelectList(db.carModels, "modelID", "modelName");
            ViewBag.subModelID = new SelectList(db.carSubModels, "subModelID", "subModelName");
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // Accept the input
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "carID,VIN,makeID,modelID,subModelID,approvalStatus,bHideCar,showCaseCarPicture,TimeStamp")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.cars.Add(car);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }


            //ViewBag.carID = new SelectList((db.carDetails));
            //ViewBag.carID = new SelectList(db.carDetails, "carID", "originalExteriorColor", car.carID);
            ViewBag.makeID = new SelectList(db.carMakers, "makeID", "makeName", car.makeID);
            ViewBag.modelID = new SelectList(db.carModels, "modelID", "modelName", car.modelID);
            ViewBag.subModelID = new SelectList(db.carSubModels, "subModelID", "subModelName", car.subModelID);
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = await db.cars.FindAsync(id);
            if (car == null)
            {
                return HttpNotFound();
            }
//            ViewBag.carID = new SelectList((db.carDetails));
            ViewBag.makeID = new SelectList(db.carMakers, "makeID", "makeName", car.makeID);
            ViewBag.modelID = new SelectList(db.carModels, "modelID", "modelName", car.modelID);
            ViewBag.subModelID = new SelectList(db.carSubModels, "subModelID", "subModelName", car.subModelID);
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "carID,VIN,makeID,modelID,subModelID,approvalStatus,bHideCar,showCaseCarPicture,TimeStamp")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
//            ViewBag.carID = new SelectList(db.carDetails, "carID", "originalExteriorColor", car.carID);
            ViewBag.makeID = new SelectList(db.carMakers, "makeID", "makeName", car.makeID);
            ViewBag.modelID = new SelectList(db.carModels, "modelID", "modelName", car.modelID);
            ViewBag.subModelID = new SelectList(db.carSubModels, "subModelID", "subModelName", car.subModelID);
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = await db.cars.FindAsync(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            Car car = await db.cars.FindAsync(id);
            db.cars.Remove(car);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExoticsOwnersRegistry/Views/Cars/Create.cshtml
@model ExoticsOwnersRegistry.Models.Car

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container-fluid">
        <h4>Car</h4>
        <hr />
        <div class="form-inline">
            <!-- Display list of car Makers-->
            <div class="form-group">
                @Html.LabelFor(model => model.carMaker.makeName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.carMaker.makeName, new { htmlAttributes = new { @class = "form-control" } })
                <!--Html.DropDownListFor(model => model.carMaker.makeName, new { htmlAttributes = new { class = "form-control" } }) -->
            </div>
            <!-- Display list of car Models -->
            <div class="form-group">
                @Html.LabelFor(model => model.carModel.modelName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.carModel.modelName, new { htmlAttributes = new { @class = "form-control" } })
                <!--Html.DropDownListFor(model => model.subModelInfo.subModelName, new { htmlAttributes = new { class = "form-control" } }) -->
            </div>
            <!-- Display list of car submodels -->
            <div class="form-group">
                @Html.LabelFor(model => model.carSubModel.subModelName, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.carSubModel.subModelName, new { htmlAttributes = new { @class = "form-control" } })
                <!--Html.DropDownListFor(model => model.carSubModel.subModelName, new { htmlAttributes = new { class = "form-control" } }) -->
            </div>
        </div>

        <p></p>

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.VIN, htmlAttributes: new { @class = "control-label col-md-2" })
                <!--               <div class="col-md-12"> -->
                @Html.EditorFor(model => model.VIN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VIN, "", new { @class = "text-danger" })
                <!--                </div> -->
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.showCaseCarPicture, htmlAttributes: new { @class = "control-label col-md-2" })
                <!--               <div class="col-md-12"> -->
                <img src="" alt="Pict Not Available" class="img-thumbnail">
                <!--@Html.EditorFor(model => model.showCaseCarPicture) -->
                @Html.ValidationMessageFor(model => model.showCaseCarPicture, "", new { @class = "text-danger" })
                <!--                </div> -->
            </div>

            <!-- Place these 2 attribute on same line -->
            <div class="form-group">
                @Html.LabelFor(model => model.approvalStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                <!--                <div class="col-md-4">-->
                @Html.EditorFor(model => model.approvalStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.approvalStatus, "", new { @class = "text-danger" })
                <!--                </div>-->
                @Html.LabelFor(model => model.bHideCar, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="checkbox">
                    @Html.EditorFor(model => model.bHideCar)
                    @Html.ValidationMessageFor(model => model.bHideCar, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <!--               @Html.LabelFor(model => model.carDetails, htmlAttributes: new { @class = "control-label col-md-2" }) -->
                <div class="btn btn-default">
                    Add Details
                    <!--                      @Html.EditorFor(model => model.carDetails) -->
                    <!--                      @Html.ValidationMessageFor(model => model.carDetails, "", new { @class = "text-danger" }) -->
                </div>
            </div>

            <div class="form-group">
                <!--                @Html.LabelFor(model => model.makeID, htmlAttributes: new { @class = "control-label col-md-2" }) -->
                <!--               <div class="col-md-12"> -->
                <div class="btn btn-link">Add Owner</div>
                <!--                </div> -->
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-12">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExoticsOwnersRegistry/Views/Cars/Delete.cshtml
@model ExoticsOwnersRegistry.Models.Car

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.carDetails.originalExteriorColor)</dt>
        <dd>@Html.DisplayFor(model => model.carDetails.originalExteriorColor)</dd>

        <dt>@Html.DisplayNameFor(model => model.VIN)
            @Html.DisplayNameFor(model => model.carMaker.makeName)</dt>
        <dd>@Html.DisplayFor(model => model.carMaker.makeName)
            @Html.DisplayFor(model => model.VIN)</dd>

        <dt>@Html.DisplayNameFor(model => model.carMaker.makeName)</dt>
        <dd>@Html.DisplayFor(model => model.carMaker.makeName)</dd>

        <dt>@Html.DisplayNameFor(model => model.carModel.modelName)</dt>
        <dd>@Html.DisplayFor(model => model.carModel.modelName)</dd>

        <dt>@Html.DisplayNameFor(model => model.carSubModel.subModelName)</dt>
        <dd>@Html.DisplayFor(model => model.carSubModel.subModelName)</dd>

        <dt>@Html.DisplayNameFor(model => model.approvalStatus)
            @Html.DisplayNameFor(model => model.carModel.modelName)</dt>
        <dd>@Html.DisplayFor(model => model.approvalStatus)</dd>

        <dt>@Html.DisplayFor(model => model.carModel.modelName)
            @Html.DisplayNameFor(model => model.bHideCar)</dt>
        <dd>@Html.DisplayFor(model => model.bHideCar)</dd>

        <dt>@Html.DisplayNameFor(model => model.carSubModel.subModelName)
            @Html.DisplayNameFor(model => model.TimeStamp)</dt>
        <dd>@Html.DisplayFor(model => model.carSubModel.subModelName)
            @Html.DisplayFor(model => model.TimeStamp)</dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ExoticsOwnersRegistry/Views/Cars/Details.cshtml
@model ExoticsOwnersRegistry.Models.Car

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.carDetails.originalExteriorColor)</dt>
        <dd>@Html.DisplayFor(model => model.carDetails.originalExteriorColor)</dd>
        <dt>@Html.DisplayNameFor(model => model.carMaker.makeName)</dt>
        <dd>@Html.DisplayFor(model => model.carMaker.makeName)</dd>
        <dt>@Html.DisplayNameFor(model => model.carModel.modelName)</dt>
        <dd>@Html.DisplayFor(model => model.carModel.modelName)</dd>
        <dt>@Html.DisplayNameFor(model => model.carSubModel.subModelName)</dt>
        <dd>@Html.DisplayFor(model => model.carSubModel.subModelName)</dd>
        <dt>@Html.DisplayNameFor(model => model.VIN)</dt>
        <dd>@Html.DisplayFor(model => model.VIN)</dd>
        <dt>@Html.DisplayNameFor(model => model.approvalStatus)</dt>
        <dd>@Html.DisplayFor(model => model.approvalStatus)</dd>
        <dt>@Html.DisplayNameFor(model => model.bHideCar)</dt>
        <dd>@Html.DisplayFor(model => model.bHideCar)</dd>
        <dt>@Html.DisplayNameFor(model => model.TimeStamp)</dt>
        <dd>@Html.DisplayFor(model => model.TimeStamp)</dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.carID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ExoticsOwnersRegistry/Views/Cars/Edit.cshtml
@model ExoticsOwnersRegistry.Models.Car

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.carID)

        <div class="form-group">
            @Html.LabelFor(model => model.makeID, "makeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("makeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.makeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VIN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VIN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VIN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modelID, "modelID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("modelID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.modelID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subModelID, "subModelID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("subModelID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.subModelID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.approvalStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.approvalStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.approvalStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bHideCar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.bHideCar)
                    @Html.ValidationMessageFor(model => model.bHideCar, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeStamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeStamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeStamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ExoticsOwnersRegistry/Views/Cars/Index.cshtml
@model IEnumerable<ExoticsOwnersRegistry.Models.Car>

<!-- 'C' indicates server side code -->
@{
    ViewBag.Title = "Index";
    @ViewBag.Message;
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.carID)</th>
        <th>@Html.DisplayNameFor(model => model.showCaseCarPicture)</th>
        <th>@Html.DisplayNameFor(model => model.carMaker.makeName)</th>
        <th>@Html.DisplayNameFor(model => model.carModel.modelName)</th>
        <th>@Html.DisplayNameFor(model => model.carSubModel.subModelName)</th>
        <th>@Html.DisplayNameFor(model => model.VIN)</th>
        <th>@Html.DisplayNameFor(model => model.carDetails)</th>
        <th>@Html.DisplayNameFor(model => model.bHideCar)</th>
        <th>@Html.DisplayNameFor(model => model.approvalStatus)</th>
        <th>@Html.DisplayNameFor(model => model.TimeStamp)</th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <!-- Attributes -->
            <td>@Html.DisplayFor(modelItem => item.carID)</td>
            <td>@Html.DisplayFor(modelItem => item.showCaseCarPicture)</td>
            <td>@Html.DisplayFor(modelItem => item.carMaker.makeName)</td>
            <td>@Html.DisplayFor(modelItem => item.carModel.modelName)</td>
            <td>@Html.DisplayFor(modelItem => item.carSubModel.subModelName)</td>
            <td>@Html.DisplayFor(modelItem => item.VIN)</td>
            <!-- Display Car Details page: (Button - Action/Record ID - controller) -->
            <td>@Html.ActionLink("Show", string.Format("Details/{0}", item.carID), "CarDetails")</td>
            <td>@Html.DisplayFor(modelItem => item.bHideCar)</td>
            <td>@Html.DisplayFor(modelItem => item.approvalStatus)</td>
            <td>@Html.DisplayFor(modelItem => item.TimeStamp)</td>

            <!-- Action menu links in 1 column -->
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.carID }) |
                @Html.ActionLink("Details", "Details", new { id=item.carID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.carID })
            </td>
        </tr>
    }
</table>